# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluate_combos_cpp <- function(x, y, combo_indices, cutoff_method) {
    .Call(`_NCVROC_evaluate_combos_cpp`, x, y, combo_indices, cutoff_method)
}

evaluate_combos_cpp_chunk <- function(x, y, min_items, max_items, cutoff_method, chunk_start, chunk_size) {
    .Call(`_NCVROC_evaluate_combos_cpp_chunk`, x, y, min_items, max_items, cutoff_method, chunk_start, chunk_size)
}

evaluate_combos_cpp_chunk_parallel <- function(x, y, min_items, max_items, cutoff_method, chunk_start, chunk_size, num_threads = -1L, grain_size = 1000L) {
    .Call(`_NCVROC_evaluate_combos_cpp_chunk_parallel`, x, y, min_items, max_items, cutoff_method, chunk_start, chunk_size, num_threads, grain_size)
}

evaluate_combos_cpp_chunk_parallel_topn <- function(x, y, min_items, max_items, cutoff_method, rank_by, top_n, prefer_fewer_items, chunk_start, chunk_size, num_threads = -1L, grain_size = 1000L) {
    .Call(`_NCVROC_evaluate_combos_cpp_chunk_parallel_topn`, x, y, min_items, max_items, cutoff_method, rank_by, top_n, prefer_fewer_items, chunk_start, chunk_size, num_threads, grain_size)
}

evaluate_combos_cpp_sparse_parallel <- function(x, y, min_items, max_items, cutoff_method, global_ranks, num_threads = -1L) {
    .Call(`_NCVROC_evaluate_combos_cpp_sparse_parallel`, x, y, min_items, max_items, cutoff_method, global_ranks, num_threads)
}

evaluate_combos_cv_cpp <- function(x, y, combo_indices, test_indices, n_folds, repeats, cutoff_method, sensitivity_min = -1.0, specificity_min = -1.0, num_threads = 1L, grain_size = 64L) {
    .Call(`_NCVROC_evaluate_combos_cv_cpp`, x, y, combo_indices, test_indices, n_folds, repeats, cutoff_method, sensitivity_min, specificity_min, num_threads, grain_size)
}

evaluate_candidate_stability_cv_cpp <- function(x, y, combo_indices, test_indices, n_folds, repeats, cutoff_method, num_threads = 1L) {
    .Call(`_NCVROC_evaluate_candidate_stability_cv_cpp`, x, y, combo_indices, test_indices, n_folds, repeats, cutoff_method, num_threads)
}

evaluate_candidate_stability_bootstrap_cpp <- function(x, y, combo_indices, train_indices, oob_indices, bootstrap_test, cutoff_method, apparent_auc, num_threads = 1L) {
    .Call(`_NCVROC_evaluate_candidate_stability_bootstrap_cpp`, x, y, combo_indices, train_indices, oob_indices, bootstrap_test, cutoff_method, apparent_auc, num_threads)
}

